#!/bin/bash
set -uo pipefail

# Install docker
# Source: https://docs.docker.com/engine/install/ubuntu/

COMMAND="docker"
DOCKER_USER="${1:-}"

OUTPUT_LOG_DIR="/var/log/install"
OUTPUT_LOG_FILENAME="${COMMAND}-$(date +%Y-%m-%d_%H-%M-%S).out"
OUTPUT_LOG_FILE="${OUTPUT_LOG_DIR}/${OUTPUT_LOG_FILENAME}"

export DEBIAN_FRONTEND=noninteractive
export NEEDRESTART_MODE=a
export NEEDRESTART_SUSPEND=1

echo-success () {
  echo -e "\e[32m ✔  $1\e[0m" >&2
}

echo-information () {
  echo -e "\e[34m ⓘ  $1\e[0m" >&2
}

echo-error () {
  echo -e "\e[31m !  $1\e[0m" >&2
}

echo-warning () {
  echo -e "\e[33m ⚠  $1\e[0m" >&2
}

echo-subsidiary () {
  echo -e "\e[37m    $1\e[0m" >&2
}

echo-step () {
  echo -e "\e[0m »  $1\e[0m" >&2
}

validate-is-root() {
  if [[ $(/usr/bin/id -u) -ne 0 ]]
  then
    echo-error "Root is required"
    exit 1
  fi
}

setup-output-log () {
  if [[ ! -d "${OUTPUT_LOG_DIR}" ]]
  then
    mkdir -p "${OUTPUT_LOG_DIR}"
  fi
  if [[ ! -f "${OUTPUT_LOG_FILE}" ]]
  then
    touch "${OUTPUT_LOG_FILE}"
  fi
  if [[ ! -w "${OUTPUT_LOG_FILE}" ]]
  then
    echo-error "Output log file is not writable"
    exit 1
  fi
}

validate-is-root
setup-output-log

echo-information "Installing ${COMMAND}"
echo-subsidiary "Logging verbose output to: ${OUTPUT_LOG_FILE}"
echo-subsidiary "Follow with: tail -f ${OUTPUT_LOG_FILE}"

echo-step "Uninstall old versions"
for PACKAGE in docker docker-engine docker.io containerd runc
do
  apt-get remove "${PACKAGE}" --yes >> "${OUTPUT_LOG_FILE}"
done

echo-step "Installing apt dependencies"
if ! (
  set -e
  apt-get update >> "${OUTPUT_LOG_FILE}"
  apt-get install --yes \
    ca-certificates \
    curl \
    gnupg \
    >> "${OUTPUT_LOG_FILE}"
)
then
  echo-error "Failed to install apt dependencies"
  exit 1
fi

echo-step "Setup the Docker repository"
if ! (
  set -e
  mkdir -m 0755 -p /etc/apt/keyrings
  curl --fail --silent --show-error --location \
    https://download.docker.com/linux/ubuntu/gpg \
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  echo \
    "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
    tee /etc/apt/sources.list.d/docker.list >> "${OUTPUT_LOG_FILE}"
)
then
  echo-error "Failed to setup the Docker repository"
  exit 1
fi

echo-step "Install Docker Engine"
if ! (
  set -e
  apt-get update >> "${OUTPUT_LOG_FILE}"
  apt-get install --yes \
    docker-ce \
    docker-ce-cli \
    containerd.io \
    docker-buildx-plugin \
    docker-compose-plugin \
    >> "${OUTPUT_LOG_FILE}"
)
then
  echo-error "Failed to setup the Docker repository"
  exit 1
fi

if [[ "${DOCKER_USER}" == "" ]]
then
  echo-warning "No docker user provided"
  echo-subsidiary "Skipping post install steps"
else

  # Post install steps
  # Source: https://docs.docker.com/engine/install/linux-postinstall/
  
  echo-step "Create the docker group"
  if ! groupadd docker
  then
    echo-warning "Failed to create the docker group"
  fi
  
  echo-step "Add user ${DOCKER_USER} to the docker group"
  if ! usermod --append --groups docker "${DOCKER_USER}"
  then
    echo-warning "Failed to add user the docker group"
  fi
  
  echo-step "Reload groups"
  newgrp docker
  if ! newgrp docker
  then
    echo-warning "Failed to reload group"
  fi
  
  # TODO: Change docker logging provider
  # Source: https://docs.docker.com/engine/install/linux-postinstall/#configure-default-logging-driver
fi

echo-success "Installed ${COMMAND}"
echo-subsidiary "$(${COMMAND} --version)"