#!/bin/bash

# Install .NET Runtime
# Source: https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu

PACKAGE="dotnet-runtime-7.0"
OUTPUT_LOG_DIR="/var/log/install"
OUTPUT_LOG_FILENAME="${PACKAGE}-$(date +%Y-%m-%d_%H-%M-%S).out"
OUTPUT_LOG_FILE="${OUTPUT_LOG_DIR}/${OUTPUT_LOG_FILENAME}"

export DEBIAN_FRONTEND=noninteractive
export NEEDRESTART_MODE=a
export NEEDRESTART_SUSPEND=1

echo-success () {
  echo -e "\e[32m ✔  $1\e[0m" >&2
}

echo-information () {
  echo -e "\e[34m ⓘ  $1\e[0m" >&2
}

echo-error () {
  echo -e "\e[31m !  $1\e[0m" >&2
}

echo-warning () {
  echo -e "\e[33m ⚠  $1\e[0m" >&2
}

echo-subsidiary () {
  echo -e "\e[37m    $1\e[0m" >&2
}

echo-step () {
  echo -e "\e[0m »  $1\e[0m" >&2
}

validate-is-root() {
  if [[ $(/usr/bin/id -u) -ne 0 ]]
  then
    echo-error "Root is required"
    exit 1
  fi
}

setup-output-log () {
  if [[ ! -d "${OUTPUT_LOG_DIR}" ]]
  then
    mkdir -p "${OUTPUT_LOG_DIR}"
  fi
  if [[ ! -f "${OUTPUT_LOG_FILE}" ]]
  then
    touch "${OUTPUT_LOG_FILE}"
  fi
  if [[ ! -w "${OUTPUT_LOG_FILE}" ]]
  then
    echo-error "Output log file is not writable"
    exit 1
  fi
}

validate-is-root
setup-output-log

echo-information "Installing ${PACKAGE}"
echo-subsidiary "Logging verbose output to: ${OUTPUT_LOG_FILE}"
echo-subsidiary "Follow with: tail -f ${OUTPUT_LOG_FILE}"

echo-step "Add the Microsoft package repository"
if ! (
  set -e
    
  declare repo_version=$(if command -v lsb_release &> /dev/null; then lsb_release -r -s; else grep -oP '(?<=^VERSION_ID=).+' /etc/os-release | tr -d '"'; fi)
  
  TEMP_FILE=$(mktemp --dry-run)

  # Download Microsoft signing key and repository
  curl "https://packages.microsoft.com/config/ubuntu/${repo_version}/packages-microsoft-prod.deb" \
    --location \
    --output "${TEMP_FILE}" \
    --show-error \
    --silent

  # Install Microsoft signing key and repository
  dpkg -i "${TEMP_FILE}" > /dev/null
  
  # Clean up
  rm "${TEMP_FILE}"
)
then
  echo-error "Failed to add the Microsoft package repository"
  exit 1
fi

echo-step "Install .NET Runtime"
if ! (
  set -e
  apt-get update >> "${OUTPUT_LOG_FILE}"
  apt-get install ${PACKAGE} --yes >> "${OUTPUT_LOG_FILE}"
  )
then
  echo-error "Failed to install .NET Runtime"
  exit 1
fi

echo-success "Installed ${PACKAGE}"
echo-subsidiary "$(dotnet --list-runtimes)"
