#!/bin/bash
set -uo pipefail

# Source: 
# https://prometheus.io/docs/guides/node-exporter/
# https://ourcodeworld.com/articles/read/1686/how-to-install-prometheus-node-exporter-on-ubuntu-2004

COMMAND="node_exporter"
SOURCE="https://github.com/prometheus/node_exporter/releases/download/v1.6.1/node_exporter-1.6.1.linux-amd64.tar.gz"
DESTINATION="/usr/local/bin/${COMMAND}"

echo-success () {
  echo -e "\e[32m ✔  $1\e[0m" >&2
}

echo-information () {
  echo -e "\e[34m ⓘ  $1\e[0m" >&2
}

echo-error () {
  echo -e "\e[31m !  $1\e[0m" >&2
}

echo-warning () {
  echo -e "\e[33m ⚠  $1\e[0m" >&2
}

echo-subsidiary () {
  echo -e "\e[37m    $1\e[0m" >&2
}

echo-step () {
  echo -e "\e[0m »  $1\e[0m" >&2
}

validate-is-root() {
  if [[ $(/usr/bin/id -u) -ne 0 ]]
  then
    echo-error "Root is required"
    exit 1
  fi
}

validate-not-installed() {
  WHICH=$(which "${COMMAND}")  
  if [[ "${WHICH}" != "" ]]
  then
    echo-warning "${COMMAND} is already installed:"
    echo-subsidiary "Path: ${WHICH}"
    exit 2
  fi
}

validate-is-root
validate-not-installed

echo-information "Installing ${COMMAND}"
echo-subsidiary "Source: ${SOURCE}"
echo-subsidiary "Destination: ${DESTINATION}"

echo-step "Downloading package"
TEMP_FILE=$(mktemp --dry-run)
if ! curl "${SOURCE}" \
       --location \
       --output "${TEMP_FILE}" \
       --show-error \
       --silent
then
  echo-error "Failed to download package"
  exit 1
fi

echo-step "Extracting package"
TEMP_DIR=$(mktemp --dry-run)
if ! (
       set -e
       mkdir "${TEMP_DIR}"
       tar \
         --extract \
         --gzip \
         --directory "${TEMP_DIR}" \
         --file "${TEMP_FILE}"
       )
then
  echo-error "Failed to extract package"
  exit 1
fi

echo-step "Installing package"
if ! cp "${TEMP_DIR}/"*"/node_exporter" "${DESTINATION}"
then
  echo-error "Failed to install package"
  exit 1
fi

echo-step "Creating user for service"
if ! (
      set -e
      useradd --no-create-home --shell /bin/false node_exporter
      (cat <<EOF
[Unit]
Description=Node Exporter
Wants=network-online.target
After=network-online.target

[Service]
User=node_exporter
Group=node_exporter
Type=simple
ExecStart=/usr/local/bin/node_exporter --web.listen-address 10.1.0.2:9100
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF
      ) | tee /etc/systemd/system/node_exporter.service   
      systemctl daemon-reload
      
      )
then
  echo-error "Failed to create user"
  exit 1
fi

echo-step "Creating service"
if ! chown node_exporter:node_exporter /usr/local/bin/node_exporter
then
  echo-error "Failed to create service"
  exit 1
fi

echo-success "Installed ${COMMAND}"
echo-subsidiary "$(${COMMAND} --version)"

echo-warning "By default the service is listening on 0.0.0.0:9100"
echo-warning "It's recommended to change to your local IP address in:"
echo-subsidiary "/etc/systemd/system/node_exporter.service"

echo-information "Start the service with:"
echo-subsidiary "sudo systemctl start node_exporter"

echo-information "Enable the service with:"
echo-subsidiary "sudo systemctl enable node_exporter"
