#!/bin/bash

echo-success () {
  echo -e "\e[32m ✔  $1\e[0m" >&2
}

echo-information () {
  echo -e "\e[34m ⓘ  $1\e[0m" >&2
}

echo-error () {
  echo -e "\e[31m !  $1\e[0m" >&2
}

echo-warning () {
  echo -e "\e[33m ⚠  $1\e[0m" >&2
}

echo-subsidiary () {
  echo -e "\e[37m    $1\e[0m" >&2
}

echo-step () {
  echo -e "\e[0m »  $1\e[0m" >&2
}

validate-is-root() {
  if [[ $(/usr/bin/id -u) -ne 0 ]]
  then
    echo-error "Root is required"
    exit 1
  fi
}

validate-is-root

echo-information "Disabling default motd"

echo-step "Removing execution permission"
if ! (
  set -e
  chmod -x /etc/update-motd.d/00-header
  chmod -x /etc/update-motd.d/10-help-text
  chmod -x /etc/update-motd.d/50-motd-news
  chmod -x /etc/update-motd.d/50-landscape-sysinfo
  chmod -x /etc/update-motd.d/90-updates-available
  )
then
  echo-error "Failed to remove execution permissions"
  exit 1
fi

echo-success "Disabled default motd ${PACKAGE}"
