name: CI/CD

on:
  push:

jobs:
    
  index:
    name: Index
    uses: ./.github/workflows/01-index.yml

  run:
    name: Run
    needs:
      - index
    uses: ./.github/workflows/02-run.yml
    strategy:
      fail-fast: false
      matrix:
        file: ${{ fromJSON(needs.index.outputs.files) }}
        os:
          - ubuntu-20.04
          - ubuntu-22.04
    with:
      file: ${{ matrix.file }}
      os: ${{ matrix.os }}

  release:
    name: Release
    if: ${{ contains(fromJSON('["main", "alpha", "beta"]'), github.ref_name) }}
    needs:
      - run
    uses: StudioLE/Actions/.github/workflows/01-semantic-release.yml@main
    secrets: inherit
    